SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER insertMembers 
AFTER INSERT 
ON MEMBERS
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('New members inserted');
END;
/
CREATE OR REPLACE TRIGGER updateMembers 
AFTER UPDATE 
ON MEMBERS
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('Status updated to both');
END;
/