@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\fragments.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\trigger.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\show all members.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\Register User.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\show all readers.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\check membership.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\renew card.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\show book availability.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\update status and fine.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\Borrow_book.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\show all borrowers.sql"
@"D:\Shihabul-Shuvo Github\DDS-Lab-Project\Library site\update library book status.sql"